server:
  port: 8179
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.219.222:3306/jade?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=false
    username: root
    password: cxt301===
    max-wait: 3000
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .ftl
    charset: utf-8
    prefix:
    template-loader-path: classpath:/templates
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
mybatis:
  type-aliases-package: com.jade.bean
fdfs:
  so-timeout: 15000
  connect-timeout: 3000
  resHost: 47.93.219.222
  pool:
    jmx-enabled: false
  tracker-list: 47.93.219.222:22122